version: "3.9"

services:
  postgres:
    image: postgres:latest
    restart: always
    container_name: pantryDB
    volumes:
      - postgres:/data/postgres
    ports:
      - 5435:5432
    environment:
      - POSTGRES_PASSWORD=admin
      - PGDATA=/data/postgres

volumes:
  postgres:
